### ISSUE TITLE
Hardcoded path in driver.py breaks simulator

### ISSUE THREAD

**Issue by jpwarren** [moorescloud/holideck#3]
When I try to test the rainbow app in Holideck, I get an OSError:

```
Traceback (most recent call last):
  File "/home/daedalus/src/holideck/bottle.py", line 763, in _handle
    return route.call(**args)
  File "/home/daedalus/src/holideck/bottle.py", line 1577, in wrapper
    rv = callback(*a, **ka)
  File "/home/daedalus/src/holideck/iotas/devices/moorescloud/holiday/driver.py", line 267, in do_runapp
    c = subprocess.call(['/home/holiday/scripts/start-app.sh', app_path], shell=False)
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

It looks like start-app.sh and stop-app.sh are missing from iotas/scripts, or is this something specific to the hardware build?

**Comment by mpesce** [comment]
The Rainbow app is actually a binary that's being invoked.  Which is why it bombs like that.

If you read the release notes to Holideck, it gives just a few apps that work.  That list is expanded now, but Rainbow, as a binary, will never be among them.

**Comment by jpwarren** [comment]
Can it die with a more informative error message then, highlighting that this is a design decision, not a bug?
